version: '3'
services:
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        stdin_open: true
        tty: true
        links:
            - db_db_1
        labels:
            traefik.frontend.rule: "Host:myadmin.zayats.org"
            traefik.port: '80'

