version: '2'

volumes:
  mysqlcsgoreview-${ENV}:

services: 

  web:
    image: globalgames/csgoreview_web:latest
    environment:
      WORDPRESS_DB_PASSWORD: 'OPf_eL5yfErR0d0N'
    labels:
      io.rancher.container.pull_image: always
      traefik.port: '80'
      traefik.domain: "${DOMAIN}" 
      traefik.frontend.rule: Host: "${DOMAIN}"
      traefik.enable: 'true'
    depends_on:
      - db

  db:
    image: mariadb:latest
    labels:
       io.rancher.container.pull_image: always
    volumes:
      - mysqlcsgoreview-${ENV}:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'OPf_eL5yfErR0d0N'
